import manifest from "../content/photos/manifest.json";

export interface PhotoExif {
  camera: string | null;
  lens: string | null;
  focalLength: string | null;
  focalLength35: string | null;
  aperture: string | null;
  shutter: string | null;
  iso: number | null;
}

export interface Photo {
  id: string;
  title: string;
  caption: string;
  location: string;
  featured: boolean;
  published: boolean;
  dateTaken: string | null;
  width: number;
  height: number;
  images: {
    thumb: string;
    full: string;
  };
  exif: PhotoExif | null;
}

// Manifest is generated by scripts/photos-ingest.mjs and already sorted
// newest-first by capture date.
export const getPhotos = (): Photo[] =>
  (manifest as Photo[]).filter((photo) => photo.published);

export const getFeaturedPhotos = (): Photo[] =>
  getPhotos().filter((photo) => photo.featured);

/** Compact settings line, e.g. "35mm · f/1.4 · 1/60s · ISO 800" */
export const formatSettings = (exif: PhotoExif | null): string =>
  exif
    ? [
        exif.focalLength,
        exif.aperture,
        exif.shutter,
        exif.iso != null ? `ISO ${exif.iso}` : null,
      ]
        .filter(Boolean)
        .join(" · ")
    : "";
